apiVersion: apps/v1
kind: Deployment
metadata:
  name: fly-pg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fly-pg
  template:
    metadata:
      labels:
        app: fly-pg
    spec:
      containers:
      - name: postgres
        image: 'postgres:14'
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5432
        envFrom:
          - secretRef:
              name: fly-pg-secret
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresdata
        resources:
          limits:
            cpu: 100m
            memory: 256M
      volumes:
      - name: postgresdata
        persistentVolumeClaim:
          claimName: fly-volume-claim