# Generated by Django 5.1 on 2024-08-18 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_userwerehouse_userwarehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_money', models.IntegerField()),
                ('income_bonus', models.IntegerField(verbose_name='bonus money per minute')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.cargo')),
            ],
        ),
    ]
