# Generated by Django 5.1 on 2024-08-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_usercargoinvestment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoimprovement',
            name='income_bonus',
            field=models.IntegerField(verbose_name='bonus income per minute'),
        ),
        migrations.AlterField(
            model_name='warehouseimprovement',
            name='income_bonus',
            field=models.IntegerField(verbose_name='bonus income per minute'),
        ),
    ]
