# Generated by Django 5.1 on 2024-08-18 20:05

import django.db.models.deletion
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_userwarehouseimprovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaneImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_plane', models.IntegerField()),
                ('bonus_type', models.CharField(choices=[(game.models.BonusType['PACKING_TIME'], 'Packing Time reduction in seconds'), (game.models.BonusType['INCOME_INCREASE'], 'More money')])),
                ('bonus_value', models.IntegerField()),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.plane')),
            ],
        ),
    ]
